
export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const CHANGEROUTE = 'CHANGEROUTE';
export const CYCLESLIDESHOW = 'CYCLESLIDESHOW';

export const TOGGLEVISIBILITY = 'TOGGLEVISIBILITY';
export const ADDTOGGLEVISIBILITY = 'ADDTOGGLEVISIBILITY';
export const REMOVETOGGLEVISIBILITY = 'REMOVETOGGLEVISIBILITY';
